/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChinhSachBaoMatRouteImport } from './routes/chinh-sach-bao-mat'
import { Route as DaLuuRouteImport } from './routes/da-luu'
import { Route as DieuKhoanSuDungRouteImport } from './routes/dieu-khoan-su-dung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhSachBaoMatRoute = ChinhSachBaoMatRouteImport.update({
  id: '/chinh-sach-bao-mat',
  path: '/chinh-sach-bao-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const DaLuuRoute = DaLuuRouteImport.update({
  id: '/da-luu',
  path: '/da-luu',
  getParentRoute: () => rootRouteImport,
} as any)
const DieuKhoanSuDungRoute = DieuKhoanSuDungRouteImport.update({
  id: '/dieu-khoan-su-dung',
  path: '/dieu-khoan-su-dung',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/da-luu': typeof DaLuuRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/da-luu': typeof DaLuuRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chinh-sach-bao-mat': typeof ChinhSachBaoMatRoute
  '/da-luu': typeof DaLuuRoute
  '/dieu-khoan-su-dung': typeof DieuKhoanSuDungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chinh-sach-bao-mat' | '/da-luu' | '/dieu-khoan-su-dung'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chinh-sach-bao-mat' | '/da-luu' | '/dieu-khoan-su-dung'
  id:
    '__root__' | '/' | '/chinh-sach-bao-mat' | '/da-luu' | '/dieu-khoan-su-dung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChinhSachBaoMatRoute: typeof ChinhSachBaoMatRoute
  DaLuuRoute: typeof DaLuuRoute
  DieuKhoanSuDungRoute: typeof DieuKhoanSuDungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-sach-bao-mat': {
      id: '/chinh-sach-bao-mat'
      path: '/chinh-sach-bao-mat'
      fullPath: '/chinh-sach-bao-mat'
      preLoaderRoute: typeof ChinhSachBaoMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/da-luu': {
      id: '/da-luu'
      path: '/da-luu'
      fullPath: '/da-luu'
      preLoaderRoute: typeof DaLuuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieu-khoan-su-dung': {
      id: '/dieu-khoan-su-dung'
      path: '/dieu-khoan-su-dung'
      fullPath: '/dieu-khoan-su-dung'
      preLoaderRoute: typeof DieuKhoanSuDungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChinhSachBaoMatRoute: ChinhSachBaoMatRoute,
  DaLuuRoute: DaLuuRoute,
  DieuKhoanSuDungRoute: DieuKhoanSuDungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
